rabbit:
  uri: ${RABBIT_URI}

http:
  auth-token: ${ACCESS_TOKEN}
  domain: ${SELF_DOMAIN}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}

endpoints:
  actuator:
    path: /mgmt

server:
  port: ${PORT:8080}